<#
.SYNOPSIS
    Build the demonstration workbook: a real .xlsm with input cells, result cells and a
    button that prices a bond through Python.

.DESCRIPTION
    Creates RYSE_Pricing_Demo.xlsm beside this script, imports the bridge and the JSON
    parser, lays the sheet out, wires the named ranges and buttons, and writes a runner
    .cmd pointing at the interpreter you name. The builder module is removed before saving,
    so the delivered workbook carries only the two modules a user needs.

    Requires Excel and, for the duration of the build only, "Trust access to the VBA project
    object model" — the script enables it and restores the previous state in a finally
    block, whatever happens.

    Nothing here is client data: the demo bond is invented. The workbook does need the
    repository beside it at run time, because the engine reads the curve files from data/.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File integrations\excel_vba\demo\Build-DemoWorkbook.ps1 `
        -PythonExe C:\Users\cnc\anaconda3\anaconda2025\python.exe
#>
param(
    [Parameter(Mandatory = $true)][string]$PythonExe,
    [string]$OutputName = "RYSE_Pricing_Demo.xlsm"
)

$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$bridge = Split-Path -Parent $here
$repo = Split-Path -Parent (Split-Path -Parent $bridge)
$secKey = "HKCU:\Software\Microsoft\Office\16.0\Excel\Security"

if (-not (Test-Path $PythonExe)) { throw "PythonExe not found: $PythonExe" }

$workbookPath = Join-Path $here $OutputName
$runnerPath = Join-Path $here "run_engine.cmd"

# The one machine-specific file. Regenerate it on any machine that runs the demo.
@("@echo off",
  "REM Generated by Build-DemoWorkbook.ps1 - the only machine-specific piece of the demo.",
  "cd /d `"$repo`" || exit /b 2",
  "set PYTHONPATH=src",
  "`"$PythonExe`" scripts\price_json.py %*") | Set-Content -Path $runnerPath -Encoding ascii

$hadVbom = $false; $oldVbom = $null
if (Test-Path $secKey) {
    $existing = Get-ItemProperty $secKey
    if ($null -ne $existing.AccessVBOM) { $hadVbom = $true; $oldVbom = $existing.AccessVBOM }
}
$excelBefore = @(Get-Process EXCEL -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Id)
$excel = $null; $wb = $null

try {
    if (-not (Test-Path $secKey)) { New-Item -Path $secKey -Force | Out-Null }
    Set-ItemProperty -Path $secKey -Name AccessVBOM -Value 1 -Type DWord

    $excel = New-Object -ComObject Excel.Application
    $excel.Visible = $false
    $excel.DisplayAlerts = $false
    $wb = $excel.Workbooks.Add()
    while ($wb.Worksheets.Count -gt 1) { $wb.Worksheets.Item($wb.Worksheets.Count).Delete() }

    $wb.VBProject.VBComponents.Import((Join-Path $bridge "JsonConverter.bas")) | Out-Null
    $wb.VBProject.VBComponents.Import((Join-Path $bridge "RysePricingBridge.bas")) | Out-Null
    $builder = $wb.VBProject.VBComponents.Import((Join-Path $here "DemoBuilder.bas"))
    $wb.VBProject.References.AddFromGuid("{420B2830-E718-11CF-893D-00A0C9054228}", 1, 0) | Out-Null

    $excel.Run("Build_DemoSheet", $runnerPath) | Out-Null
    $wb.VBProject.VBComponents.Remove($builder)      # ship only the bridge + parser

    if (Test-Path $workbookPath) { Remove-Item $workbookPath -Force }
    $wb.SaveAs($workbookPath, 52)                    # 52 = xlOpenXMLWorkbookMacroEnabled
    $wb.Close($false)
    $wb = $null

    "workbook : $workbookPath"
    "runner   : $runnerPath"
    "engine   : $PythonExe"
    "size     : $([math]::Round((Get-Item $workbookPath).Length / 1KB, 1)) KB"
}
finally {
    if ($null -ne $wb) { try { $wb.Close($false) } catch {} }
    if ($null -ne $excel) { try { $excel.Quit() } catch {} }
    if ($null -ne $excel) { try { [void][System.Runtime.InteropServices.Marshal]::ReleaseComObject($excel) } catch {} }
    [GC]::Collect(); [GC]::WaitForPendingFinalizers()
    Get-Process EXCEL -ErrorAction SilentlyContinue |
        Where-Object { $excelBefore -notcontains $_.Id } |
        ForEach-Object { try { Stop-Process -Id $_.Id -Force } catch {} }

    if ($hadVbom) { Set-ItemProperty -Path $secKey -Name AccessVBOM -Value $oldVbom -Type DWord }
    else { try { Remove-ItemProperty -Path $secKey -Name AccessVBOM -ErrorAction Stop } catch {} }
}
