"""Package the source tree as a zip for a colleague — code only, no prose.

    python scripts/make_code_zip.py

Written for Liping's request of 2026-09-26: *"目前所有的 code 给我一个 zip,不要任何 pdf 和
markdown"*. She is writing the modelling manual and wants to read the code, not our write-ups.

WHAT GOES IN
    src/ tests/ scripts/ integrations/     the code, including the VBA bridge and its fixtures
    conftest.py pytest.ini requirements.txt  without these the suite will not even collect

WHAT STAYS OUT, and why each one
    *.md, *.pdf     her explicit request. That includes integrations/excel_vba/README.md and
                    the demo script, which are the only two prose files inside the code tree.
    __pycache__, *.pyc   build residue; it also leaks absolute paths from this machine.
    data/           NOT code, and it is the client's portfolio. See the warning below.
    outputs/        generated, and regenerated by the drivers in seconds.
    docs/, .git/    prose and history.

⚠️ **WITHOUT data/ THE SUITE DOES NOT PASS, and she has to be told.** Measured on 2026-09-26:
`414 passed, 60 skipped, 88 failed, 32 errors` — the failures are FileNotFound on the
holdings workbook and the curve exports, not defects. With `data/` in place it is 594 passed.
The script prints this so whoever sends the zip says it in the covering message.

⭐ The exclusion is VERIFIED BY REOPENING THE ARCHIVE, not by trusting the walk that built it.
A glob that silently matches nothing is this project's most repeated failure; here it would
put a PDF in a colleague's hands after a message promising none.
"""
from __future__ import annotations

import datetime
import os
import pathlib
import zipfile

ROOT = pathlib.Path(__file__).resolve().parents[1]

#: Directories copied whole (minus the exclusions below).
CODE_DIRS = ("src", "tests", "scripts", "integrations")

#: Loose files at the repo root. Each is required to RUN, not to read:
#: conftest puts src/ on the path, pytest.ini stops the collector walking staging copies,
#: requirements.txt is the environment.
ROOT_FILES = ("conftest.py", "pytest.ini", "requirements.txt")

#: Suffixes refused anywhere in the archive. The check at the end re-derives this from the
#: written file rather than from the walk.
BANNED_SUFFIXES = (".md", ".pdf", ".pyc", ".pyo")
BANNED_DIR_NAMES = ("__pycache__", ".git", ".pytest_cache", ".venv", ".claude")


def wanted(path: pathlib.Path) -> bool:
    if any(part in BANNED_DIR_NAMES for part in path.parts):
        return False
    return path.suffix.lower() not in BANNED_SUFFIXES


def main():
    stamp = datetime.date.today().isoformat()
    top = f"ryse_pricing_code_{stamp}"
    out = ROOT / f"{top}.zip"

    members: list[tuple[pathlib.Path, str]] = []
    for d in CODE_DIRS:
        base = ROOT / d
        if not base.exists():
            raise SystemExit(f"missing source directory: {d}")
        for p in sorted(base.rglob("*")):
            if p.is_file() and wanted(p):
                members.append((p, f"{top}/{p.relative_to(ROOT).as_posix()}"))
    for f in ROOT_FILES:
        p = ROOT / f
        if not p.exists():
            raise SystemExit(f"missing root file: {f}")
        members.append((p, f"{top}/{f}"))

    if out.exists():
        out.unlink()
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for src, arc in members:
            z.write(src, arc)

    # ---- verify by REOPENING, not by trusting the walk that just ran -------------
    with zipfile.ZipFile(out) as z:
        names = z.namelist()
        bad_suffix = [n for n in names
                      if pathlib.PurePosixPath(n).suffix.lower() in BANNED_SUFFIXES]
        bad_dir = [n for n in names
                   if any(part in BANNED_DIR_NAMES for part in pathlib.PurePosixPath(n).parts)]
        stray = [n for n in names
                 if n.split("/", 1)[1].split("/", 1)[0] not in CODE_DIRS + ROOT_FILES]
        if bad_suffix or bad_dir or stray:
            out.unlink()
            for n in (bad_suffix + bad_dir + stray)[:10]:
                print("   REFUSED:", n)
            raise SystemExit("archive rejected and deleted: it contained excluded content")

    by_ext: dict[str, int] = {}
    for n in names:
        by_ext[pathlib.PurePosixPath(n).suffix or "(none)"] = \
            by_ext.get(pathlib.PurePosixPath(n).suffix or "(none)", 0) + 1

    print(f"wrote {out.name}  ({len(names)} files, {out.stat().st_size / 1024:.0f} KB)")
    for ext, n in sorted(by_ext.items(), key=lambda kv: -kv[1]):
        print(f"   {ext:<8} {n:4d}")
    print("\n   verified by reopening the archive: no .md, no .pdf, no __pycache__")
    # ASCII ONLY below this line. This console encodes as GBK, and the first version of
    # this script died on a warning-sign glyph -- swallowing the one message it exists to
    # print. Third time this project has hit the same codec: pytest.ini's em dash and
    # release_facts' redirected stdout were the others.
    print("\n   !! SAY THIS IN THE COVERING MESSAGE:")
    print("   The zip has no data/ : it is the client's portfolio, not code. Without it")
    print("   `pytest` gives roughly 414 passed / 88 failed / 32 errors, and every failure")
    print("   is a missing input file rather than a defect. Drop the project's data/ folder")
    print("   in beside src/ and it is 594 passed.")


if __name__ == "__main__":
    main()
